
# Run this first section if the model was called from the command line
if (exists("SYSTEM_COMMAND_ARGS")) {
  
  if (length(SYSTEM_COMMAND_ARGS) >= 1) SCENARIO_NAME <- SYSTEM_COMMAND_ARGS[1] else SCENARIO_NAME <- BASE_SCENARIO_BASE_NAME
  if (length(SYSTEM_COMMAND_ARGS) >= 2) SCENARIO_YEAR <- SYSTEM_COMMAND_ARGS[2] else SCENARIO_YEAR <- BASE_SCENARIO_BASE_YEAR
  if (length(SYSTEM_COMMAND_ARGS) >= 3) SCENARIO_RUN_FIRMSYN <- as.logical(SYSTEM_COMMAND_ARGS[3]) else SCENARIO_RUN_FIRMSYN <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 4) SCENARIO_RUN_SCM     <- as.logical(SYSTEM_COMMAND_ARGS[4]) else SCENARIO_RUN_SCM <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 5) SCENARIO_RUN_FTTM    <- as.logical(SYSTEM_COMMAND_ARGS[5]) else SCENARIO_RUN_FTTM <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 6) SCENARIO_RUN_TT      <- as.logical(SYSTEM_COMMAND_ARGS[6]) else SCENARIO_RUN_TT <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 7) SCENARIO_RUN_DB      <- as.logical(SYSTEM_COMMAND_ARGS[7]) else SCENARIO_RUN_DB <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 8) SCENARIO_REFERENCE_NAME <- SYSTEM_COMMAND_ARGS[8] else SCENARIO_REFERENCE_NAME <- ifelse(SCENARIO_NAME == BASE_SCENARIO_BASE_NAME, "Validation", BASE_SCENARIO_BASE_NAME)
  if (length(SYSTEM_COMMAND_ARGS) >= 9) SCENARIO_REFERENCE_YEAR <- as.integer(SYSTEM_COMMAND_ARGS[9]) else SCENARIO_REFERENCE_YEAR <- as.integer(BASE_SCENARIO_BASE_YEAR)

} else {
  
  SCENARIO_NAME <- BASE_SCENARIO_BASE_NAME
  SCENARIO_YEAR <- BASE_SCENARIO_BASE_YEAR
  SCENARIO_RUN_FIRMSYN <- TRUE
  SCENARIO_RUN_SCM <- TRUE
  SCENARIO_RUN_FTTM <- TRUE
  SCENARIO_RUN_TT <- TRUE
  SCENARIO_RUN_DB <- TRUE
  SCENARIO_REFERENCE_NAME <- ifelse(SCENARIO_NAME == BASE_SCENARIO_BASE_NAME, "Validation", BASE_SCENARIO_BASE_NAME)
  SCENARIO_REFERENCE_YEAR <- as.integer(BASE_SCENARIO_BASE_YEAR)
  
}

SCENARIO_INPUT_PATH <- file.path(SYSTEM_APP_PATH, "scenarios", SCENARIO_NAME, "inputs")
SCENARIO_OUTPUT_PATH <- file.path(SYSTEM_APP_PATH, "scenarios", SCENARIO_NAME, "outputs")
SCENARIO_BASE_OUTPUT_PATH <- file.path(SYSTEM_APP_PATH, "scenarios", BASE_SCENARIO_BASE_NAME, "outputs")
SCENARIO_LOG_PATH <- file.path(SCENARIO_OUTPUT_PATH, "log")
SCENARIO_BASEFIRMS <- file.path(SCENARIO_BASE_OUTPUT_PATH, SYSTEM_FIRMSYN_OUTPUTNAME)

# Switches for the Dashboard components: TRUE and the content for that model step is rendered in the dashboard
SCENARIO_DB_FIRMSYN <- TRUE
SCENARIO_DB_SCM <- TRUE
SCENARIO_DB_FTTM <- TRUE
SCENARIO_DB_TT <- TRUE
SCENARIO_DB_CALIBRATION <- ifelse(SCENARIO_NAME == BASE_SCENARIO_BASE_NAME, TRUE, FALSE)
SCENARIO_DB_REFERENCE <- ifelse(SCENARIO_NAME == BASE_SCENARIO_BASE_NAME, FALSE, TRUE)
SCENARIO_DB_SPREADSHEET <- TRUE

